"""Stack-aware `doctor` for gobbonet_agentic.

GENERATED BY gen_aw_doctor.py -- DO NOT EDIT.
Regenerate it with the generator named above; a hand-edit here is reverted by
the next run and fails the parity gate.

Why a doctor exists at all: the aw* bricks are designed to COMPOSE, so the
interesting failures live BETWEEN them. "gobbonet_agentic is installed" is not the useful
fact -- "gobbonet_agentic is installed and the thing it pairs with is not" is. This reports
the whole stack, not just itself.

stdlib only, on purpose: a diagnostic that cannot run because a dependency is
missing is worthless precisely when you need it.
"""
from __future__ import annotations

import importlib.util
import shutil
import sys

#: Frozen from AitherOS/config/ecosystem.yaml at generation time. A shipped
#: package cannot read the registry, and a doctor that guessed at the family
#: would go stale in silence. Regenerate to update.
SELF = 'gobbonet_agentic'
FAMILY = ['awask', 'awbac', 'awbrowse', 'awdit', 'awevolve', 'awfind', 'awgit', 'awgraph',
 'awiam', 'awkno', 'awm', 'awmail', 'awnboard', 'awnest', 'awnet', 'awprism',
 'awreason', 'awrecover', 'awrecurse', 'awrelay', 'awrena', 'awrepl', 'awresearch',
 'awrise', 'awrun', 'awscreen', 'awseal', 'awshare', 'awtoll', 'awtunnel',
 'awvision', 'awvoice', 'awwall']
PAIRS_WITH = []


def _installed(mod: str) -> "str | None":
    """Version if importable, else None. Never raises -- a broken sibling must
    not take the diagnostic down with it."""
    try:
        if importlib.util.find_spec(mod) is None:
            return None
    except (ImportError, ValueError):
        return None
    try:
        from importlib.metadata import PackageNotFoundError, version
        try:
            return version(mod)
        except PackageNotFoundError:
            return "installed"
    except Exception:
        return "installed"


def report(out=None) -> int:
    """Print the stack picture. 0 = this brick and its pairs are present."""
    out = out or sys.stdout
    print(f"{SELF} doctor", file=out)

    mine = _installed(SELF)
    print(f"  self       {SELF} {mine or 'NOT IMPORTABLE'}", file=out)
    shim = shutil.which(SELF)
    print(f"  command    {shim or 'not on PATH'}", file=out)

    # The stack. Siblings this brick pairs with are called out separately,
    # because a missing pair is a REASON, while a missing unrelated brick is
    # just a fact about your machine.
    missing_pairs, present = [], []
    for name in FAMILY:
        v = _installed(name)
        if v:
            present.append(name)
        elif name in PAIRS_WITH:
            missing_pairs.append(name)
    print(f"  stack      {len(present)}/{len(FAMILY)} aw* packages installed",
          file=out)
    if present:
        print(f"             {' '.join(sorted(present))}", file=out)

    local = _local_checks()
    for line in local:
        print(f"  {line}", file=out)

    if mine is None:
        print(f"\nverdict: {SELF} itself is not importable. Reinstall it before "
              f"anything else here means much.", file=out)
        return 1
    if missing_pairs:
        print(f"\nverdict: {SELF} works, but pairs with "
              f"{', '.join(sorted(missing_pairs))} which "
              f"{'is' if len(missing_pairs) == 1 else 'are'} not installed. "
              f"That is a capability you are missing, not an error.", file=out)
        return 0
    print(f"\nverdict: {SELF} and everything it pairs with are present.", file=out)
    return 0


def _local_checks() -> "list[str]":
    """Per-brick checks, if this package defines them.

    Kept as a HOOK rather than generated guesses: the generator knows the family
    from the registry, but it does not know what gobbonet_agentic needs at runtime, and a
    doctor that invented config requirements would be confidently wrong. A
    package supplies `_doctor_local()` returning display lines; absent, the
    stack picture above still stands on its own.
    """
    try:
        mod = importlib.import_module(f"{SELF}.doctor_local")
    except Exception:
        return []
    try:
        return list(mod._doctor_local())
    except Exception as exc:                       # noqa: BLE001
        return [f"local     checks raised {type(exc).__name__}: {exc}"]


def main(argv: "list[str] | None" = None) -> int:
    return report()


if __name__ == "__main__":
    raise SystemExit(main())
